name: Deploy to Development
on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Deploy
          if: github.ref == 'refs/heads/development'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "DEPLOY_URL"