name: Deploy

on:
    push:
      branches: [main, development]
       
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Install root dependencies
          run: npm install

        - name: Install client dependencies
          run: cd client && npm install
  
        - name: Install server dependencies
          run: cd server && npm install

        - name: Deploy
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"
  