name: Deploy

on:
    push:
      branches: [main, development]
    pull_request:
      branches: [main, development]
       
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: install dependencies
          run: |
            npm install

        - name: Deploy
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"
  